# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('posted_on',)},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('post_date',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user',)},
        ),
    ]
